// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5nUMplRghN2M5EHhfLgOlZah_zLuuNrc',
    appId: '1:101611854024:web:3b30c5fe03e9238ef7adfd',
    messagingSenderId: '101611854024',
    projectId: 'mebook-f79be',
    authDomain: 'mebook-f79be.firebaseapp.com',
    storageBucket: 'mebook-f79be.appspot.com',
    measurementId: 'G-P3EL700EN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFQFXWvcqaVhWQwlYHNifTJkYi13JoZc',
    appId: '1:101611854024:android:179b70841a623814f7adfd',
    messagingSenderId: '101611854024',
    projectId: 'mebook-f79be',
    storageBucket: 'mebook-f79be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG2y9R02ZgthhNaVLzFtyYSDce1M-Khg0',
    appId: '1:101611854024:ios:2425fd7b8ec87db6f7adfd',
    messagingSenderId: '101611854024',
    projectId: 'mebook-f79be',
    storageBucket: 'mebook-f79be.appspot.com',
    iosBundleId: 'com.example.mebook',
  );
}
